version: '3'
services:
  app:
    image: "${REPO_PATH}${IMAGE}:${TAG}"
    #build: .
    env_file:
      - .env
    stdin_open: true
    tty: true
#    command: >
#      bash -c "sleep 1000000"
    command: "sleep 100m"
    networks:
      - platform_integration
      #platform_integration:
      #  ipv4_address: 192.168.19.51

networks:
  platform_integration:
    external: true
